# Generated by Django 2.1.1 on 2018-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(max_length='200', verbose_name='课程详情'),
        ),
    ]
